resilience4j.circuitbreaker:
    instances:
        workItemService:           
            failureRateThreshold: 50
            slidingWindowSize: 5
            permittedNumberOfCallsInHalfOpenState: 3
            waitDurationInOpenState: 20s
            automaticTransitionFromOpenToHalfOpenEnabled: true